version: '3.8'

services:
  redis:
    image: redis
    container_name:
      "notification_redis"
    restart: unless-stopped
    ports:
      - 6379:6379

  backend:
    container_name:
      "notification_backend"
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: no
    networks:
      - backend
      - db
    expose:
      - "8000"
    depends_on:
      - db
  bot:
    container_name:
      "telegram"
    build:
      context: telegram
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - backend
    networks:
      - backend

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - db

networks:
  backend:
    driver: bridge
  db:
    driver: bridge