# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "dmiv",
  "password": "123456"
}
###

POST http://127.0.0.1:8000/api/auth/token
Accept: application/json

{
    "username": "dmiv",
    "password": "123456"
}
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkbWl2IiwiZXhwIjoxNzI2NTA4OTM5fQ.nGVBs2ZW0SEIDOVb29qpHZlSwQI86OD2dpYR0bHpyTg
GET http://127.0.0.1:8000/api/notifications/
Authorization: Bearer {{token}}

###


