# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "dmiv",
  "password": "123456"
}
###
POST http://127.0.0.1:8000/api/auth/token
Accept: application/json

{
    "username": "dmiv",
    "password": "123456"
}
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkbWl2IiwiZXhwIjoxNzI2NzM4NDQyfQ.6VIKSfqzsMcOUZFIygYlX4sKJb60ox_ZjKkLKZZjc0g
GET http://127.0.0.1:8000/api/auth/telegram/link/
Accept: application/json
Authorization: Bearer {{token}}
###
POST http://127.0.0.1:8000/api/auth/telegram/link/
Content-Type: application/json

{
  "data": {
    "id": 972834722,
    "is_bot": "False",
    "first_name": "Дмитрий",
    "last_name": "Счислёнок",
    "username": "tyrannozavr",
    "language_code": "ru",
    "is_premium": "None",
    "added_to_attachment_menu": null,
    "can_join_groups": null,
    "can_read_all_group_messages": null,
    "supports_inline_queries": null,
    "can_connect_to_business": null,
    "has_main_web_app": null,
    "access_token": "hello_world_ept",
    "hash": "a6c62d8e300f56c667cfa6b2a75b0b01c610494a870e55f9649bb9d10704bbf8"
  }
}



