@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkbWl2MiIsImV4cCI6MTcyNjUxMDc3NX0.kO9WhHwxWurKJk-1Cxw6UCjm_PQixZQ9c1DKORt7pN0
GET http://127.0.0.1:8000/api/notifications/
Authorization: Bearer {{token}}
###
POST http://127.0.0.1:8000/api/notifications/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "New Feature Release",
  "description": "We are excited to announce the release of our new feature!",
  "tags": [
    "update",
    "feature",
    "release"
  ]
}
###
