@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkbWl2IiwiZXhwIjoxNzI2NjExMjE1fQ.w21Ek9yYInH9yVZXMq0NuyatxxKDAPD5mB-wBtxPdx8
GET http://127.0.0.1:8000/api/notifications/
Authorization: Bearer {{token}}
###
GET http://127.0.0.1:8000/api/notifications/tags/hello_world/
Authorization: Bearer {{token}}
###

POST http://127.0.0.1:8000/api/notifications/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "New Feature Release",
  "description": "We are excited to announce the release of our new feature!",
  "tags": [
    "sdf",
    "sdf2",
    "release"
  ]
}
###
PATCH http://127.0.0.1:8000/api/notifications/3/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "New Feature Release 2.0",
  "description": "We are excited to announce the release of our new feature!",
  "tags": [
    "update",
    "hello_world",
    "most_important",
    "study"
  ]
}
###
DELETE http://127.0.0.1:8000/api/notifications/4/
Authorization: Bearer {{token}}
Content-Type: application/json